### ISSUE TITLE
In generate_traceroutes - Raise KeyError does not catch exception it says it does

### ISSUE THREAD

**Issue by crockk** [crockk/graphical-traceroute#2]
The exception raised at [this line ](https://github.com/crockk/graphical-traceroute/blob/68de1512ceecc2f89408d0b01daa620d084dbc4b/backend/app.py#L172) occurs when there is a dataset which has both nulls and not-null values, in other words, it may occur when there is no data for a particular interval. Might be fixed by #1 when it gets done

**Comment by bakedSpaceTime** [comment]
Exception replaced with continue statement [here](https://github.com/crockk/graphical-traceroute/blob/f59488e1eb14f51c13e1066fe4969cf1b083a07f/backend/app.py#L173). No need to raise exception, just continue to next interval. Fixed in this commit https://github.com/crockk/graphical-traceroute/commit/7144bd0d62765f58c305ee9dd95f7fce133b9163
